title: Wead.
email: your-email@domain.com
description: "A simple and clean jekyll theme."
twitter_username: kevyder
github_username:  kevyder
baseurl: /wead
paginate: 5
paginate_path: "/wead/page:num/"
plugins: [jekyll-paginate]

markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
